[project]
name = "mojo-protobuf"
version = "0.1.0"
description = "A pure-Mojo Protocol Buffers implementation"
authors = ["Manuel Saelices <msaelices@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
platforms = ["linux-64", "osx-arm64"]
license = "MIT"
readme = "README.md"

[dependencies]
max = "*"

[tasks]
test-wire = "mojo run -I src test/test_wire.mojo"
test-fields = "mojo run -I src test/test_fields.mojo"
test-message = "mojo run -I src test/test_message.mojo"
test = { depends-on = ["test-wire", "test-fields", "test-message"] }
format = "mojo format ./"
